### ISSUE TITLE
Use busybox for cleanupProxy image

### ISSUE THREAD

**Issue by ghost** [DoD-Platform-One/monitoring#10]
# Feature Request

## Why

We should be able to use an existing community image (like busybox) to perform the cleanupProxy actions.

## Proposed Solution

Use the alpine container image in [values.yaml](chart/values.yaml):

```yaml
cleanupProxy:
      image:
        registry: registry1.dso.mil
        repository: ironbank/opensource/alpinelinux/alpine
        tag: 3.19.1
        sha: ""
        pullPolicy: IfNotPresent
```

and update the [job-patchWebhook.yaml](chart/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml):

```yaml
- name: cleanup-proxy
  command:
  - /bin/sh
  - -c
  - |
    until wget --spider -q http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
    echo \"Sidecar available, sleeping 10 seconds then killing istio proxy...\";
    sleep 10;
    x=$(echo $?); wget --post-data='' -qO- http://localhost:15020/quitquitquit && exit $x
```
